apiVersion: apps/v1
kind: Deployment
metadata:
  name: shinyproxy
  namespace: shiny
spec:
  selector:
    matchLabels:
      run: shinyproxy
  replicas: 1
  template:
    metadata:
      labels:
        run: shinyproxy
    spec:
      containers:
      - name: shinyproxy
        image: gcr.io/apt-subset-313012/shinyproxy-application:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
      - name: kube-proxy-sidecar
        image: gcr.io/apt-subset-313012/kube-proxy-sidecar:0.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
