proxy:
  port: 8080
  container-backend: kubernetes
  kubernetes:
    internal-networking: true
    url: http://localhost:8001
    namespace: shiny
    image-pull-policy: IfNotPresent
  specs:
  - id: Aimmobius
    display-name: Aimmobius
    description: Aimmobius
    container-cmd: ["R", "-e", "shiny::runApp('/app/shiny')"]
    container-image: gcr.io/apt-subset-313012/aimmo

logging:
  file:
    shinyproxy.log
