proxy:
  title: Aimmobius.com
  hide-navbar: true
  landing-page: /app/aimmo
  heartbeat-rate: 10000
  heartbeat-timeout: 600000
  container-wait-time: 100000
  container-backend: kubernetes
  kubernetes:
    internal-networking: true
    url: http://localhost:8001
    namespace: shiny
    image-pull-policy: IfNotPresent
  specs:
  - id: Aimmobius
    container-cmd: ["R", "-e", "shiny::runApp('/app/shiny')"]
    container-image: gcr.io/apt-subset-313012/aimmo

logging:
  file:
    shinyproxy.log
